class Selectors {
    static logo = 'img[alt="Cars.com"]'
    static pageMenuTitles = '.header-link'
    static researchHeading = '.spark-heading-1.sds-page-section__title'
    static makeMenu = '#make-select'
    static makeMenuOption = '#make-select> option'
    static modelMenu = '#model-select'
    static modelMenuOption = '#model-select> option'
    static yearMenu = '#year-select'
    static yearMenuOption = '#year-select> option'
    static noOptionSelectedInMakeMenu = '.sds-input-container sds-input-container--dropdown'
    static researchButton = 'button:contains("Research")'
    static selectedOptionsTitle1 = '.spark-heading-1.sds-page-section__title'
    static selectedOptionsTitle2 = '.hubcap-type-heading-headline'
    static trimOptions = '.trim-compare-list'
    static carCharacteristics = '.key-spec'
    static compareTwoCars = '.tools-section a[href*="compare"]'
    static comparePageTitle = '.spark-heading-2.sds-page-section__title'
    static addCar1MakeMenu = '.sds-text-field[data-qa="make-selector-vehicle_1"]'
    static addCar1ModelMenu = '.sds-text-field[data-qa="model-selector-vehicle_1"]'
    static addCar1YearMenu = '.sds-text-field[data-qa="year-selector-vehicle_1"]'
    static addCar2MakeMenu = '.sds-text-field[data-qa="make-selector-vehicle_2"]'
    static addCar2ModelMenu = '.sds-text-field[data-qa="model-selector-vehicle_2"]'
    static addCar2YearMenu = '.sds-text-field[data-qa="year-selector-vehicle_2"]'
    static comparisonButton = 'button:contains("comparison")'
    static carComparisonPage = '.vehicle-cards [data-slugs'
}
export default Selectors;